name: franka_multi_camera

image_shape: [3, 480, 640]  # C, H, W
joint_dim: 8  # Adjust based on your robot's DOF
action_dim: 8  # Adjust based on your action space

dataset_path: /mnt/SharedDrive/franka_diff2d_processed.zarr

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    left_camera:
      shape: ${task.image_shape}
      type: rgb
    wrist_camera:
      shape: ${task.image_shape}
      type: rgb
    right_camera:
      shape: ${task.image_shape}
      type: rgb
    joint_states:
      shape: [8]
      type: low_dim
  action: 
    shape: [8]

# Dummy env_runner - replace with your actual environment if available
# env_runner:
#   _target_: diffusion_policy.env_runner.base_image_runner.BaseImageRunner

dataset:
  _target_: diffusion_policy.dataset.franka_dataset.FrankaDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: False  # Disabled to avoid memory issues with large datasets
  seed: 42
  val_ratio: 0.1
  max_train_episodes: null
